using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PatrolBehaviour : MonoBehaviour {

    public float speed;
    public Transform[] moveSpots;
    public float startWaittime;

    private float waitTime;
    private int randomSpots;

    void Start()
    {
        //take a random position between the spots created
        waitTime = startWaittime;
        randomSpots = Random.Range(0, moveSpots.Length);
    }

    void Update()
    {
        //move to a random spot generated by randoSpots variable
        transform.position = Vector3.MoveTowards(transform.position,moveSpots[randomSpots].position, speed * Time.deltaTime);

        if (Vector3.Distance(transform.position,moveSpots[randomSpots].position  ) < 0.2f)
        {
            if (waitTime <= 0)
            {
                randomSpots = Random.Range(0, moveSpots.Length);
                waitTime = startWaittime;
            }
            else
            {
                waitTime -= Time.deltaTime;
            }
        }
    }


}
